# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RACIANTAU
email: gabriel@raciantau.com
author: That Rock
description: >
  was born in early 2016 when a PRIMORDIAL SOUP of deep MELANCHOLY,
  a pervading and explicitly late-20th-century-alt-inspired ENNUI, and CIGARETTE WITHDRAWALS was
  shot with the LIGHTNING BOLT of INSPIRATION in the form of two CUTE CHARACTER DESIGNS. In
  these pages we'll be exploring themes of ISOLATION, ALIENATION, the FUTURE of our SPECIES,
  keeping to the CENTER, and YOUR MOM with a cute smile plastered over the unshakable sense that
  our best days are <strike>behind us</strike> a LIE WE TELL OURSELVES. Welcome!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raciantau.com" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  stories:
  comics:
    output: true
    permalink: /comics/:path/

future: true
repository: ra-rock/ra-studios

# Build settings
paginate: 5
paginate_path: "/blog/page:num/"

uploads_dir: "img/content"

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
